// src/config/api.js
const GATEWAY = import.meta.env.VITE_API_GATEWAY

// Define relative paths for Amplify / SigV4 calls
export const ENDPOINTS = {
  MARGANA_TERMS_AUDIT: import.meta.env.VITE_API_ENDPOINT_MARGANA_TERMS_AUDIT,
  MARGANA_TERMS_AUDIT_GUEST: import.meta.env.VITE_API_ENDPOINT_MARGANA_TERMS_AUDIT_GUEST,
  // removed in place for MARGANA_SUBMISSION_GUEST (MARGANA_SUBMISSION: import.meta.env.VITE_API_ENDPOINT_MARGANA_SUBMISSION)
  MARGANA_SUBMISSION_GUEST: import.meta.env.VITE_API_ENDPOINT_MARGANA_SUBMISSION_GUEST,
}

export const API = {
  GATEWAY,
  MARGANA_COMMIT_WORDS: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_COMMIT_WORDS}`,
  MARGANA_ACCEPT_INVITE: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_ACCEPT_INVITE}`,
  MARGANA_CREATE_GROUP: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_CREATE_GROUP}`,
  MARGANA_SEND_GROUP_INVITE: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_SEND_GROUP_INVITE}`,
  MARGANA_SEND_FRIEND_INVITE: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_SEND_FRIEND_INVITE}`,
  MARGANA_UPDATE_GROUP_PENDING: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_UPDATE_GROUP_PENDING}`,
  MARGANA_TERMS_AUDIT: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_TERMS_AUDIT}`,
  MARGANA_GET_GROUP: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_GET_GROUP}`,
  MARGANA_METRIC: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_METRIC}`,
  USER_SETTINGS: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_USER_SETTINGS}`,
  PROFILE: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_PROFILE}`,
  CHECK_USERNAME: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_CHECK_USERNAME}`,
  MARGANA_SUBMISSION: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_SUBMISSION}`,
  MARGANA_SUBMISSION_COMMIT: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_SUBMISSION_COMMIT}`,
  MARGANA_DASHBOARD_SUMMARY: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_MARGANA_DASHBOARD_SUMMARY}`,
  LEADERBOARDS: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}`,
  LEADERBOARDS_PUBLIC: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS_PUBLIC}`,
  LEADERBOARD_CHECK_NAME: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/check-name`,
  LEADERBOARD_JOIN: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/join`,
  LEADERBOARD_INVITATIONS: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/invitations`,
  LEADERBOARD_REQUESTS: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/requests`,
  LEADERBOARD_RESOLVE_REQUEST: (id: string, sub: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/requests/${sub}`,
  LEADERBOARD_SCORES: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/scores`,
  LEADERBOARD_HISTORY: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/history`,
  LEADERBOARD_INVITE: `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/invite`,
  LEADERBOARD_MEMBERS: (id: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/members`,
  LEADERBOARD_UPDATE_MEMBER: (id: string, sub: string) => `${GATEWAY}${import.meta.env.VITE_API_ENDPOINT_LEADERBOARDS}/${id}/members/${sub}`,
  ENDPOINTS
}

export const  MyAmplify = {
  USER_POOL_ID: import.meta.env.VITE_USER_POOL_ID,
  USER_POOL_CLIENT_ID: import.meta.env.VITE_USER_POOL_CLIENT_ID,
  IDENTITY_POOL_ID: import.meta.env.VITE_IDENTITY_POOL_ID,
  GATEWAY
}

export const Bucket = {
  MARGANA_WORD_GAME: import.meta.env.VITE_MARGANA_WORD_GAME,
  MARGANA_GAME_RESULTS: import.meta.env.VITE_MARGANA_GAME_RESULTS,
  MARGANA_ANALYTICS: import.meta.env.VITE_MARGANA_ANALYTICS_BUCKET,
}
