name: Preprod Frontend Build And Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  preprod-deploy:
    uses: ./.github/workflows/frontend-build-deploy.yml
    with:
      environment_name: preprod
      build_command: npm run build:preprod
      artifact_name: dist-preprod
      deploy_enabled: true
