name: Prod Frontend Build And Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  prod-pr-build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/frontend-build-deploy.yml
    with:
      environment_name: prod
      build_command: npm run build:prod
      artifact_name: dist-prod
      deploy_enabled: false

  prod-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/frontend-build-deploy.yml
    with:
      environment_name: prod
      build_command: npm run build:prod
      artifact_name: dist-prod
      deploy_enabled: true
